### ISSUE TITLE
DetectionMode Repeating does not call onStartDetect after a card removal

### ISSUE THREAD

**Issue by amessara-billettiqueservices** [eclipse-keyple/keyple-service-java-lib#52]
Hello,
When using a reader that implements **_WaitForCardInsertionAutonomous_** and calling startDetection with a **_DetectionMode.REPEATING_** , card detection is not actually started after a card removal.
In this type of reader **_WaitForCardInsertionStateAdapter_** does not have a monitoring job, so nothing is started when entering this state.

**Comment by jeanpierrefortune** [comment]
Hello Aghilas,
Can you tell us more about the choice of the "autonomous" mode?
As it is designed, it is intended for readers where the ISO14443 scanning is operated by the terminal without the possibility to start or stop it explicitly. The typical example is the standard NFC functionality of Android terminals.
Is it you who makes the code of the plugin? **_WaitForCardInsertionBlockingSpi_** or **_WaitForCardInsertionNonBlockingSpi_** may be more suitable?
Best regards

**Comment by jeanpierrefortune** [comment]
Hello Aghilas,
Just to be sure, do you have a call to `finalizeCardProcessing` (from `ObservableCardReader`) at the end of card processing by the business process?
Best regards

**Comment by amessara-billettiqueservices** [comment]
Hello Jean-Pierre,
Yes indeed we have a call to `finalizeCardProcessing` otherwise the state machine stays in `WAIT_FOR_CARD_PROCESSING`.
Regards,

**Comment by andrei-cristea** [comment]
Hello Aghilas,

It seems that the internal API of your reader works in "single shot" mode and that it is necessary to call the "start detection" method after each processing to restart the card detection.

This situation was not foreseen when the "Keyple Plugin API" was designed. It is therefore necessary to carry out an in-depth analysis on this subject.

In the meantime, you can manually manage the `REPEATING` mode at the application level by systematically calling the `startCardDetection(SINGLE_SHOT)` method after each call to the `finalizeCardProcessing()` method.

Regards

**Comment by amessara-billettiqueservices** [comment]
Hello Andrei,
Thank you for your response.
This is exactly what we do and is a satisfactory enough workaround. I will be happy to assist if you need any further information.
Regards,

**Comment by jeanpierrefortune** [comment]
Hello Aghilas,

After a more in-depth analysis, it turns out that it is the plugin's responsibility to maintain continuous observation of the cards as long as the service does not ask it to stop via the `onStopDetection()` method of the `ObservableReaderSpi`.

Indeed, as you pointed out, the FlowBird plugin has a shortcoming in this regard, in the sense that it stops the observation on its own after detecting a card.

We have made a correction in version `3.2.2` of Keyple Service to ensure that the `onStopDetection()` method is properly called whenever necessary.

Feel free to reopen if needed.

Regards
